name: trust_edge_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  dio: 5.3.3
  flutter_secure_storage: 9.0.0
  equatable: 2.0.5
  dartz: 0.10.1
  flutter: 
    sdk: flutter
  country_code_picker: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: AlexandriaFLF
      fonts:
        - asset: assets/fonts/alexandria_flf/AlexandriaFLF-Bold.ttf
          weight: 700
        - asset: assets/fonts/alexandria_flf/AlexandriaFLF-Italic.ttf
          style: italic
        - asset: assets/fonts/alexandria_flf/AlexandriaFLF.ttf

